llama_fine_tune:
  prompt_template: "llama_fine_tune/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "/mnt/workspace/LLaMA-Factory/checkpoints/qwen_sft/"
    model_kwargs:
      torch_dtype: "bfloat16"
      trust_remote_code: True
    max_new_tokens: 2048
    top_p: 1.0
  pretty_name: "LLaMA_fine_tune"